[tool.poetry]
name = "bikeshop"
version = "0.1.0"
description = ""
authors = ["baevtimofey <tim-baev@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ruff = "^0.6.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
