class UserRepositoryImpl:
    async def create_user(self, name: str, email: str, password: str) -> None: ...
    async def get_user_by_id(self, id: int) -> users.User: ...
    async def get_all_users(self) -> typing.List[users.User]: ...
    async def delete_user(self, id: int) -> None: ...
